apiVersion: v1
kind: Secret
metadata:
  name: {{ include "escai.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "escai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ include "escai.databaseUrl" . | quote }}
  {{- end }}
  {{- if .Values.mongodb.enabled }}
  mongodb-url: {{ include "escai.mongodbUrl" . | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-url: {{ include "escai.redisUrl" . | quote }}
  {{- end }}
  {{- if .Values.influxdb.enabled }}
  influxdb-url: {{ include "escai.influxdbUrl" . | quote }}
  influxdb-token: {{ .Values.influxdb.adminUser.token | quote }}
  {{- end }}
  {{- if .Values.neo4j.enabled }}
  neo4j-url: {{ include "escai.neo4jUrl" . | quote }}
  neo4j-password: {{ .Values.neo4j.neo4j.password | quote }}
  {{- end }}
  jwt-secret-key: {{ .Values.escai.auth.jwtSecretKey | default (randAlphaNum 32) | quote }}