# Production environment values for ESCAI Framework

escai:
  replicaCount: 5

  image:
    tag: "latest"

  ingress:
    hosts:
      - host: api.escai.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: escai-production-tls
        hosts:
          - api.escai.example.com

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  autoscaling:
    enabled: true
    minReplicas: 5
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 70

  env:
    ESCAI_ENV: "production"
    LOG_LEVEL: "INFO"

  # Production security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

# High availability and performance for production
postgresql:
  primary:
    persistence:
      size: 50Gi
      storageClass: "fast-ssd"
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  readReplicas:
    replicaCount: 2
    persistence:
      size: 50Gi
      storageClass: "fast-ssd"

mongodb:
  persistence:
    size: 100Gi
    storageClass: "fast-ssd"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  replicaSet:
    enabled: true
    replicas:
      secondary: 2
      arbiter: 1

redis:
  master:
    persistence:
      size: 20Gi
      storageClass: "fast-ssd"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  replica:
    replicaCount: 2
    persistence:
      size: 20Gi
      storageClass: "fast-ssd"

influxdb:
  persistence:
    size: 200Gi
    storageClass: "fast-ssd"
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi

neo4j:
  volumes:
    data:
      defaultStorageClass:
        requests:
          storage: 100Gi
        storageClassName: "fast-ssd"
  resources:
    cpu: "2000m"
    memory: "8Gi"

prometheus:
  server:
    persistentVolume:
      size: 100Gi
      storageClass: "fast-ssd"
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi
    retention: "30d"

grafana:
  persistence:
    size: 10Gi
    storageClass: "fast-ssd"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Enable network policies for production
networkPolicy:
  enabled: true

# Enable pod security policy
podSecurityPolicy:
  enabled: true
