apiVersion: v1
kind: ServiceAccount
metadata:
  name: escai-service-account
  namespace: escai
  labels:
    app.kubernetes.io/name: escai
    app.kubernetes.io/component: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: escai
  name: escai-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: escai-role-binding
  namespace: escai
subjects:
  - kind: ServiceAccount
    name: escai-service-account
    namespace: escai
roleRef:
  kind: Role
  name: escai-role
  apiGroup: rbac.authorization.k8s.io
