# ESCAI Framework Configuration Example
# This is a comprehensive example configuration file showing all available options

# Environment settings
environment: development # development, testing, staging, production
debug: true # Enable debug mode (automatically disabled in production)
log_level: DEBUG # DEBUG, INFO, WARNING, ERROR, CRITICAL

# Database configuration
database:
  # PostgreSQL - Primary structured data storage
  postgres_host: localhost
  postgres_port: 5432
  postgres_database: escai
  postgres_username: escai_user
  postgres_password: change_me_in_production # Will be encrypted when saved
  postgres_pool_size: 10
  postgres_max_overflow: 20

  # MongoDB - Unstructured data and logs
  mongodb_host: localhost
  mongodb_port: 27017
  mongodb_database: escai_logs
  mongodb_username: null
  mongodb_password: null # Will be encrypted if set
  mongodb_replica_set: null

  # Redis - Caching and real-time data
  redis_host: localhost
  redis_port: 6379
  redis_database: 0
  redis_password: null # Will be encrypted if set
  redis_pool_size: 10

  # InfluxDB - Time-series metrics
  influxdb_host: localhost
  influxdb_port: 8086
  influxdb_database: escai_metrics
  influxdb_username: null
  influxdb_password: null # Will be encrypted if set
  influxdb_retention_policy: 30d

  # Neo4j - Graph data and relationships
  neo4j_uri: bolt://localhost:7687
  neo4j_username: neo4j
  neo4j_password: change_me_in_production # Will be encrypted when saved
  neo4j_database: neo4j
  neo4j_pool_size: 10

# API configuration
api:
  host: 0.0.0.0 # Bind address
  port: 8000 # API port
  workers: 4 # Number of worker processes
  reload: false # Auto-reload on code changes (development only)

  # Rate limiting
  rate_limit_requests: 100 # Requests per minute per IP
  rate_limit_window: 60 # Rate limit window in seconds

  # CORS settings
  cors_origins:
    - "*" # Allowed origins (restrict in production)
  cors_methods:
    - GET
    - POST
    - PUT
    - DELETE
  cors_headers:
    - "*"

  # Request/Response limits
  max_request_size: 10485760 # 10MB max request size
  request_timeout: 30 # Request timeout in seconds

  # WebSocket settings
  websocket_max_connections: 100 # Max concurrent WebSocket connections
  websocket_heartbeat_interval: 30 # Heartbeat interval in seconds

# Security configuration
security:
  # JWT Configuration
  jwt_secret_key: change_me_to_a_secure_random_key_in_production # Will be encrypted
  jwt_algorithm: HS256
  jwt_access_token_expire_minutes: 30
  jwt_refresh_token_expire_days: 7

  # TLS Configuration
  tls_enabled: false # Enable TLS encryption (required in production)
  tls_cert_file: null # Path to TLS certificate file
  tls_key_file: null # Path to TLS private key file
  tls_ca_file: null # Path to TLS CA certificate file

  # Password policies
  password_min_length: 8
  password_require_uppercase: true
  password_require_lowercase: true
  password_require_numbers: true
  password_require_symbols: true

  # Session management
  session_timeout_minutes: 60
  max_login_attempts: 5
  lockout_duration_minutes: 15

  # PII Detection and Masking
  pii_detection_enabled: true
  pii_masking_enabled: true
  pii_sensitivity_level: medium # low, medium, high

  # Audit logging
  audit_enabled: true
  audit_retention_days: 90

# Monitoring and observability configuration
monitoring:
  # Performance monitoring
  monitoring_enabled: true
  monitoring_overhead_threshold: 0.1 # Max 10% performance overhead
  sampling_rate: 1.0 # 100% sampling (reduce in production)

  # Metrics collection
  metrics_enabled: true
  metrics_interval_seconds: 60

  # Health checks
  health_check_enabled: true
  health_check_interval_seconds: 30

  # Alerting
  alerting_enabled: true
  alert_thresholds:
    cpu_usage: 80.0 # CPU usage percentage
    memory_usage: 85.0 # Memory usage percentage
    disk_usage: 90.0 # Disk usage percentage
    error_rate: 5.0 # Error rate percentage

# Machine learning configuration
ml:
  # Model settings
  model_cache_enabled: true
  model_cache_size: 100 # Number of models to cache
  model_update_interval_hours: 24 # How often to update models

  # Training settings
  training_enabled: true
  training_batch_size: 32
  training_epochs: 10
  validation_split: 0.2 # 20% of data for validation

  # Prediction settings
  prediction_confidence_threshold: 0.7 # Minimum confidence for predictions
  ensemble_size: 5 # Number of models in ensemble

# Custom application settings
# Add your own configuration options here
custom_settings:
  # Example custom settings
  feature_flags:
    experimental_features: false
    beta_ui: false

  # Integration settings
  integrations:
    slack_webhook_url: null
    email_notifications: true

  # Performance tuning
  performance:
    cache_ttl_seconds: 300
    batch_processing_size: 1000
