global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # ESCAI API metrics
  - job_name: "escai-api"
    static_configs:
      - targets: ["escai-api:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # MongoDB metrics (if using mongodb_exporter)
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongo:27017"]
    scrape_interval: 30s

  # InfluxDB metrics
  - job_name: "influxdb"
    static_configs:
      - targets: ["influxdb:8086"]
    scrape_interval: 30s

  # Neo4j metrics
  - job_name: "neo4j"
    static_configs:
      - targets: ["neo4j:7474"]
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
